# Generated by Django 3.0.6 on 2020-06-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
                ('chair', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Учебное подразделение',
                'verbose_name_plural': 'Учебные подразделения',
            },
        ),
    ]
